# Setup
title: Animated octo spork
url: https://yurtsiv.me
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
ga_analytics: UA-176265471-1

# Specify the author for blog posts
author:
  name: Animated octo spork
  url: https://github.com/yurtsiv
  email: yurtsiv.stepan@gmail.com

# Custom vars
version: 1.0.0
